echo Getting AV_Champs_Elysees ...
wget "https://opendata.paris.fr/explore/dataset/comptages-routiers-permanents/download/?format=csv&disjunctive.libelle=true&disjunctive.etat_trafic=true&disjunctive.libelle_nd_amont=true&disjunctive.libelle_nd_aval=true&q=av_champs&refine.libelle=AV_Champs_Elysees&timezone=Europe/Paris&lang=fr&use_labels_for_header=true&csv_separator=%3B"  -o /dev/null -O "../data/AV_Champs_Elysees.csv"

echo Getting Convention ...
wget "https://opendata.paris.fr/explore/dataset/comptages-routiers-permanents/download/?format=csv&disjunctive.libelle=true&disjunctive.etat_trafic=true&disjunctive.libelle_nd_amont=true&disjunctive.libelle_nd_aval=true&q=Lecourbe-Convention&refine.libelle_nd_amont=Lecourbe-Convention&refine.libelle_nd_aval=Convention-Blomet&timezone=Europe/Paris&lang=fr&use_labels_for_header=true&csv_separator=%3B"  -o /dev/null -O "../data/Convention.csv"

echo Getting Sts_Peres ...
wget "https://opendata.paris.fr/explore/dataset/comptages-routiers-permanents/download/?format=csv&disjunctive.libelle=true&disjunctive.etat_trafic=true&disjunctive.libelle_nd_amont=true&disjunctive.libelle_nd_aval=true&q=Sts_Peres-Voltaire&refine.libelle_nd_aval=Sts_Peres-Universite&timezone=Europe/Paris&lang=fr&use_labels_for_header=true&csv_separator=%3B"  -o /dev/null -O "../data/Sts_Peres.csv"
